import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>          
        <div className="bg-purple-800 p-6">
        <nav>
          <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4"> 
              <Link href="/" className="flex items-center space-x-3 rtl:space-x-reverse">
                  <Image
                    src="/Blogger.png"
                    alt="Globe icon"
                    width={200}
                    height={60}
                  />
                  <span className="self-center text-2xl font-semibold whitespace-nowrap dark:text-white"></span>
              </Link>

          </div>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
